import pygame
import time as t
import os
cur_dir = os.path.dirname(__file__)

pygame.init()

while True:
    clock = pygame.time.Clock()
    world = pygame.display.set_mode((800, 800))
    cutsceneimg1 = pygame.image.load(f"{cur_dir}/Cutscene1 Frame1.png")
    cutscenesimg1 = pygame.transform.scale(cutsceneimg1, (800, 800))
    world.blit(cutscenesimg1, ((0, 0)))
    pygame.display.flip()
    pygame.time.delay(500)
    cutsceneimg2 = pygame.image.load(f"{cur_dir}/Cutscene1 Frame2.png")
    cutscenesimg2 = pygame.transform.scale(cutsceneimg2, (800, 800))
    world.blit(cutscenesimg2, ((0, 0)))
    pygame.display.flip()
    pygame.time.delay(500)
    cutsceneimg3 = pygame.image.load(f"{cur_dir}/Cutscene1 Frame3.png")
    cutscenesimg3 = pygame.transform.scale(cutsceneimg3, (800, 800))
    world.blit(cutscenesimg3, ((0, 0)))
    pygame.display.flip()
    pygame.time.delay(500)
    cutsceneimg4 = pygame.image.load(f"{cur_dir}/Cutscene1 Frame4.png")
    cutscenesimg4 = pygame.transform.scale(cutsceneimg4, (800, 800))
    world.blit(cutscenesimg4, ((0, 0)))
    pygame.display.flip()
    pygame.time.delay(500)
    cutsceneimg5 = pygame.image.load(f"{cur_dir}/Cutscene1 Frame3.png")
    cutscenesimg5 = pygame.transform.scale(cutsceneimg5, (800, 800))    
    world.blit(cutscenesimg5, ((0, 0)))
    pygame.display.flip()
    pygame.time.delay(500)
    cutsceneimg6 = pygame.image.load(f"{cur_dir}/Cutscene1 Frame5.png")
    cutscenesimg6 = pygame.transform.scale(cutsceneimg6, (800, 800))
    world.blit(cutscenesimg6, ((0, 0)))
    pygame.display.flip()
    pygame.time.delay(500)
    cutsceneimg7 = pygame.image.load(f"{cur_dir}/Cutscene1 Frame6.png")
    cutscenesimg7 = pygame.transform.scale(cutsceneimg7, (800, 800))
    world.blit(cutscenesimg7, ((0, 0)))
    pygame.display.flip()
    pygame.time.delay(500)
    clock.tick(60)